name: Feature Request 🚀
description: Suggest an idea for this project or propose a new feature
title: "[FEATURE] "
body:
  - type: textarea
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is, and what you expect to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What problem does this feature solve?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Checklist
      description: Before submitting the issue, please make sure you have done the following
      options:
        - label: I have searched the issues of this repository and believe that this is not a duplicate
          required: true
        - label: I have read the CONTRIBUTING and CODE_OF_CONDUCT documents
          required: true

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
