name: SonarQube Scan

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

permissions:
  pull-requests: read

jobs:
  Analyze:
    name: Analyze code with SonarQube
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: -Dsonar.projectKey=pierregueroult_next-launch_bfa13057-ca32-4aa4-b80d-9bd64034deac
